config/routes.rb
Click2Interact::Application.routes.draw do

  resources :announcement_messages, path: 'announcements' do
    get :unshow
    # shows list of past announcements for the current user
    collection do
      get :past
    end
    member do
      get :recipients
      post :resend
    end
  end

  resources :groups

  resources :paper_forms, path: 'forms' do
    resources :assignments do
      member do
        get :take
        post :complete
        get :completed
      end
    end
    resources :response_sets

    get :possible_assignees

  end

  resources :quizzes do
    resources :assignments do
      member do
        get :take
        post :complete
        get :completed
      end
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "pages#index"
  match '/terms' => "pages#terms"
  match '/about' => "pages#about"
  match '/faq' => "pages#faq"
  match '/changelog' => "pages#changelog"

  # authentification and registration
  devise_for :users, controllers: { registrations: "registrations", confirmations: "confirmations" } do
    # sign-up with PIN
    get "users/sign_up_with_pin", to: "registrations#new_pin"
  end
  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end

  resources :users, :only => [:show, :index, :edit] do
    resources :assignments do
      collection do
        get 'for'
        get 'by'
      end
    end
    get 'recipient_list'
    put 'change'

    get 'new_child'
    post 'create_child'

    resources :announcement_messages, path: :announcements, only: [:resend]  do
      post :resend
    end

    resources :announcement_messages, path: :announcements, only: [:index]
    
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :text_messages, :path => 'sms', :only => [:index, :new, :create, :destroy]

  namespace :admin do
    resources :reports
    resources :users, :only => [:show, :edit, :index, :new, :create, :destroy] do
      put 'change'
      get 'new_child'
      post 'create_child'
      member do
        post 'approve'
        post 'disapprove'
        post 'notify'
      end
    end
    resources :user_imports

    root to: "users#index"
  end

  scope '/admin' do
    resources :reports do
      resources :assignments
    end
  end

  namespace :teacher do
    resources :reports, only: [:index], controller: 'report_submissions' do
      resources :report_submissions, only: [:new, :show, :create, :destroy] , path: 'submissions'
      get "submissions", controller: 'report_submissions'
    end
  end

  namespace :parent do
    resources :reports, only: [:index], controller: 'report_submissions' do
      resources :report_submissions, only: [:show] , path: 'submissions'
      get "submissions", controller: 'report_submissions'
    end
  end

end
#== Route Map
# Generated on 15 Oct 2012 21:50
#
#                                 POST   /groups(.:format)                                         groups#create
#                       new_group GET    /groups/new(.:format)                                     groups#new
#                      edit_group GET    /groups/:id/edit(.:format)                                groups#edit
#                           group GET    /groups/:id(.:format)                                     groups#show
#                                 PUT    /groups/:id(.:format)                                     groups#update
#                                 DELETE /groups/:id(.:format)                                     groups#destroy
#      take_paper_form_assignment GET    /forms/:paper_form_id/assignments/:id/take(.:format)      assignments#take
#  complete_paper_form_assignment POST   /forms/:paper_form_id/assignments/:id/complete(.:format)  assignments#complete
# completed_paper_form_assignment GET    /forms/:paper_form_id/assignments/:id/completed(.:format) assignments#completed
#          paper_form_assignments GET    /forms/:paper_form_id/assignments(.:format)               assignments#index
#                                 POST   /forms/:paper_form_id/assignments(.:format)               assignments#create
#       new_paper_form_assignment GET    /forms/:paper_form_id/assignments/new(.:format)           assignments#new
#      edit_paper_form_assignment GET    /forms/:paper_form_id/assignments/:id/edit(.:format)      assignments#edit
#           paper_form_assignment GET    /forms/:paper_form_id/assignments/:id(.:format)           assignments#show
#                                 PUT    /forms/:paper_form_id/assignments/:id(.:format)           assignments#update
#                                 DELETE /forms/:paper_form_id/assignments/:id(.:format)           assignments#destroy
#        paper_form_response_sets GET    /forms/:paper_form_id/response_sets(.:format)             response_sets#index
#                                 POST   /forms/:paper_form_id/response_sets(.:format)             response_sets#create
#     new_paper_form_response_set GET    /forms/:paper_form_id/response_sets/new(.:format)         response_sets#new
#    edit_paper_form_response_set GET    /forms/:paper_form_id/response_sets/:id/edit(.:format)    response_sets#edit
#         paper_form_response_set GET    /forms/:paper_form_id/response_sets/:id(.:format)         response_sets#show
#                                 PUT    /forms/:paper_form_id/response_sets/:id(.:format)         response_sets#update
#                                 DELETE /forms/:paper_form_id/response_sets/:id(.:format)         response_sets#destroy
#   paper_form_possible_assignees GET    /forms/:paper_form_id/possible_assignees(.:format)        paper_forms#possible_assignees
#                     paper_forms GET    /forms(.:format)                                          paper_forms#index
#                                 POST   /forms(.:format)                                          paper_forms#create
#                  new_paper_form GET    /forms/new(.:format)                                      paper_forms#new
#                 edit_paper_form GET    /forms/:id/edit(.:format)                                 paper_forms#edit
#                      paper_form GET    /forms/:id(.:format)                                      paper_forms#show
#                                 PUT    /forms/:id(.:format)                                      paper_forms#update
#                                 DELETE /forms/:id(.:format)                                      paper_forms#destroy
#                            root        /                                                         home#index
#                            root        /                                                         pages#index
#                new_user_session GET    /users/sign_in(.:format)                                  devise/sessions#new
#                    user_session POST   /users/sign_in(.:format)                                  devise/sessions#create
#            destroy_user_session DELETE /users/sign_out(.:format)                                 devise/sessions#destroy
#                   user_password POST   /users/password(.:format)                                 devise/passwords#create
#               new_user_password GET    /users/password/new(.:format)                             devise/passwords#new
#              edit_user_password GET    /users/password/edit(.:format)                            devise/passwords#edit
#                                 PUT    /users/password(.:format)                                 devise/passwords#update
#        cancel_user_registration GET    /users/cancel(.:format)                                   devise/registrations#cancel
#               user_registration POST   /users(.:format)                                          devise/registrations#create
#           new_user_registration GET    /users/sign_up(.:format)                                  devise/registrations#new
#          edit_user_registration GET    /users/edit(.:format)                                     devise/registrations#edit
#                                 PUT    /users(.:format)                                          devise/registrations#update
#                                 DELETE /users(.:format)                                          devise/registrations#destroy
#            for_user_assignments GET    /users/:user_id/assignments/for(.:format)                 assignments#for
#             by_user_assignments GET    /users/:user_id/assignments/by(.:format)                  assignments#by
#                user_assignments GET    /users/:user_id/assignments(.:format)                     assignments#index
#                                 POST   /users/:user_id/assignments(.:format)                     assignments#create
#             new_user_assignment GET    /users/:user_id/assignments/new(.:format)                 assignments#new
#            edit_user_assignment GET    /users/:user_id/assignments/:id/edit(.:format)            assignments#edit
#                 user_assignment GET    /users/:user_id/assignments/:id(.:format)                 assignments#show
#                                 PUT    /users/:user_id/assignments/:id(.:format)                 assignments#update
#                                 DELETE /users/:user_id/assignments/:id(.:format)                 assignments#destroy
#                           users GET    /users(.:format)                                          users#index
#                            user GET    /users/:id(.:format)                                      users#show
#                         quizzes GET    /quizzes(.:format)                                        quizzes#index
#                                 POST   /quizzes(.:format)                                        quizzes#create

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  helper_method :mailbox, :conversation
  before_filter :authenticate_user!
  # load_and_authorize_resource

  def new
    # list of users current user can send a message to
    @users = User.all
  end

  def create
    recipients_names = conversation_params(:recipients).split(',')
    recipients = User.where(name: recipients_names).all
    conversation = current_user.send_message(recipients, *conversation_params(:body, :subject)).conversation

    redirect_to conversation
  end

  def reply
    current_user.reply_to_conversation(conversation, *message_params(:body, :subject))
    redirect_to conversation
  end

  def trash
    conversation.move_to_trash(current_user)
    redirect_to :conversations
  end

  def untrash
    conversation.untrash(current_user)
    redirect_to :conversations
  end

  private

  def mailbox
    @mailbox ||= current_user.mailbox
  end

  def conversation
    @conversation ||= mailbox.conversations.find(params[:id])
  end

  def conversation_params(*keys)
    fetch_params(:conversation, *keys)
  end

  def message_params(*keys)
    fetch_params(:message, *keys)
  end

  def fetch_params(key, *subkeys)
    params[key].instance_eval do
      case subkeys.size
      when 0 then self
      when 1 then self[subkeys.first]
      else subkeys.map{|k| self[k] }
      end
    end
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.haml
= content_tag_for(:li, conversation) do |conversation|
  %p
    = link_to conversation.subject, conversation
    |
    - if conversation.is_completely_trashed?(current_user)
      = link_to 'Untrash', [:untrash, conversation], method: :post
    - else
      = link_to 'Move to trash', [:trash, conversation], method: :post

app/views/conversations/_form.html.haml
= simple_form_for(:conversation, :url => :conversations) do |f|
  = f.error_notification

  .form-inputs
    = f.input :recipients
    = f.input :subject
    = f.input :body, :as => :text,  :input_html => { :rows => 8 , :class => "span6", value: ""}

  .form-actions
    = f.button :submit, class: 'btn-primary'
    = link_to 'Cancel', conversations_path, class: 'btn btn-danger'


.users-list
  
  %table.table.table-bordered.table-striped
    %th
      List of users
    - @users.each do |user|
      %tr
        %td= user.name

app/views/conversations/_home_page_conversations.html.haml
%table.table#home_page_conversations
  %thead
    %th Subject
    %th Received
  %tbody
    - @messages.each do |msg|
      %tr
        %td= link_to msg.subject, msg.conversation
        %td= l msg.created_at, format: :medium

app/views/conversations/index.html.haml
.page-header
  %h1
    Conversations

- unless mailbox.inbox.empty?
  %section
    %h2
      Inbox

    %table.table
      - mailbox.inbox.each do |m|
        %tr
          %td= m.originator.name
          %td= m.subject
          %td{:width=>"30%"}
            = btn_link_to 'Show', m
            = btn_link_to 'Trash', trash_conversation_path(m), :confirm => 'Are you sure?', :method => :post

- unless mailbox.sentbox.empty?
  %section
    %h2
      Sent
    %table.table
      - mailbox.sentbox.each do |m|
        %tr
          %td= m.originator.name
          %td= m.subject
          %td{:width=>"30%"}
            = btn_link_to 'Show', m
            = btn_link_to 'Trash', trash_conversation_path(m), :confirm => 'Are you sure?', :method => :post

- unless mailbox.trash.empty?
  %section
    %h2
      Trash

    %table.table
      -  mailbox.trash.each do |m|
        %tr
          %td= m.originator.name
          %td= m.subject
          %td{:width=>"30%"}
            = btn_link_to 'Show', m
            = btn_link_to 'UnTrash', untrash_conversation_path(m), :confirm => 'Are you sure?', :method => :post

= btn_link_to 'Start Conversation', :new_conversation

app/views/conversations/new.html.haml
%h1 Start Conversation
= render 'form'

app/views/conversations/show.html.haml
%p#notice= notice

%h1= conversation.subject

.conversation_area
  %ul.conversation_trail
    = content_tag_for(:li, conversation.receipts_for(current_user)) do |receipt|
      - message = receipt.message
      -# %h3= message.subject
      %strong= message.sender.name
      %p= message.body

= render 'messages/form', conversation: conversation