config/routes.rb
Click2Interact::Application.routes.draw do

  resources :announcement_messages, path: 'announcements' do
    get :unshow
    # shows list of past announcements for the current user
    collection do
      get :past
    end
    member do
      get :recipients
      post :resend
    end
  end

  resources :groups

  resources :paper_forms, path: 'forms' do
    resources :assignments do
      member do
        get :take
        post :complete
        get :completed
      end
    end
    resources :response_sets

    get :possible_assignees

  end

  resources :quizzes do
    resources :assignments do
      member do
        get :take
        post :complete
        get :completed
      end
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "pages#index"
  match '/terms' => "pages#terms"
  match '/about' => "pages#about"
  match '/faq' => "pages#faq"
  match '/changelog' => "pages#changelog"

  # authentification and registration
  devise_for :users, controllers: { registrations: "registrations", confirmations: "confirmations" } do
    # sign-up with PIN
    get "users/sign_up_with_pin", to: "registrations#new_pin"
  end
  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end

  resources :users, :only => [:show, :index, :edit] do
    resources :assignments do
      collection do
        get 'for'
        get 'by'
      end
    end
    get 'recipient_list'
    put 'change'

    get 'new_child'
    post 'create_child'

    resources :announcement_messages, path: :announcements, only: [:resend]  do
      post :resend
    end

    resources :announcement_messages, path: :announcements, only: [:index]
    
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :text_messages, :path => 'sms', :only => [:index, :new, :create, :destroy]

  namespace :admin do
    resources :reports
    resources :users, :only => [:show, :edit, :index, :new, :create, :destroy] do
      put 'change'
      get 'new_child'
      post 'create_child'
      member do
        post 'approve'
        post 'disapprove'
        post 'notify'
      end
    end
    resources :user_imports

    root to: "users#index"
  end

  scope '/admin' do
    resources :reports do
      resources :assignments
    end
  end

  namespace :teacher do
    resources :reports, only: [:index], controller: 'report_submissions' do
      resources :report_submissions, only: [:new, :show, :create, :destroy] , path: 'submissions'
      get "submissions", controller: 'report_submissions'
    end
  end

  namespace :parent do
    resources :reports, only: [:index], controller: 'report_submissions' do
      resources :report_submissions, only: [:show] , path: 'submissions'
      get "submissions", controller: 'report_submissions'
    end
  end

end
#== Route Map
# Generated on 15 Oct 2012 21:50
#
#                                 POST   /groups(.:format)                                         groups#create
#                       new_group GET    /groups/new(.:format)                                     groups#new
#                      edit_group GET    /groups/:id/edit(.:format)                                groups#edit
#                           group GET    /groups/:id(.:format)                                     groups#show
#                                 PUT    /groups/:id(.:format)                                     groups#update
#                                 DELETE /groups/:id(.:format)                                     groups#destroy
#      take_paper_form_assignment GET    /forms/:paper_form_id/assignments/:id/take(.:format)      assignments#take
#  complete_paper_form_assignment POST   /forms/:paper_form_id/assignments/:id/complete(.:format)  assignments#complete
# completed_paper_form_assignment GET    /forms/:paper_form_id/assignments/:id/completed(.:format) assignments#completed
#          paper_form_assignments GET    /forms/:paper_form_id/assignments(.:format)               assignments#index
#                                 POST   /forms/:paper_form_id/assignments(.:format)               assignments#create
#       new_paper_form_assignment GET    /forms/:paper_form_id/assignments/new(.:format)           assignments#new
#      edit_paper_form_assignment GET    /forms/:paper_form_id/assignments/:id/edit(.:format)      assignments#edit
#           paper_form_assignment GET    /forms/:paper_form_id/assignments/:id(.:format)           assignments#show
#                                 PUT    /forms/:paper_form_id/assignments/:id(.:format)           assignments#update
#                                 DELETE /forms/:paper_form_id/assignments/:id(.:format)           assignments#destroy
#        paper_form_response_sets GET    /forms/:paper_form_id/response_sets(.:format)             response_sets#index
#                                 POST   /forms/:paper_form_id/response_sets(.:format)             response_sets#create
#     new_paper_form_response_set GET    /forms/:paper_form_id/response_sets/new(.:format)         response_sets#new
#    edit_paper_form_response_set GET    /forms/:paper_form_id/response_sets/:id/edit(.:format)    response_sets#edit
#         paper_form_response_set GET    /forms/:paper_form_id/response_sets/:id(.:format)         response_sets#show
#                                 PUT    /forms/:paper_form_id/response_sets/:id(.:format)         response_sets#update
#                                 DELETE /forms/:paper_form_id/response_sets/:id(.:format)         response_sets#destroy
#   paper_form_possible_assignees GET    /forms/:paper_form_id/possible_assignees(.:format)        paper_forms#possible_assignees
#                     paper_forms GET    /forms(.:format)                                          paper_forms#index
#                                 POST   /forms(.:format)                                          paper_forms#create
#                  new_paper_form GET    /forms/new(.:format)                                      paper_forms#new
#                 edit_paper_form GET    /forms/:id/edit(.:format)                                 paper_forms#edit
#                      paper_form GET    /forms/:id(.:format)                                      paper_forms#show
#                                 PUT    /forms/:id(.:format)                                      paper_forms#update
#                                 DELETE /forms/:id(.:format)                                      paper_forms#destroy
#                            root        /                                                         home#index
#                            root        /                                                         pages#index
#                new_user_session GET    /users/sign_in(.:format)                                  devise/sessions#new
#                    user_session POST   /users/sign_in(.:format)                                  devise/sessions#create
#            destroy_user_session DELETE /users/sign_out(.:format)                                 devise/sessions#destroy
#                   user_password POST   /users/password(.:format)                                 devise/passwords#create
#               new_user_password GET    /users/password/new(.:format)                             devise/passwords#new
#              edit_user_password GET    /users/password/edit(.:format)                            devise/passwords#edit
#                                 PUT    /users/password(.:format)                                 devise/passwords#update
#        cancel_user_registration GET    /users/cancel(.:format)                                   devise/registrations#cancel
#               user_registration POST   /users(.:format)                                          devise/registrations#create
#           new_user_registration GET    /users/sign_up(.:format)                                  devise/registrations#new
#          edit_user_registration GET    /users/edit(.:format)                                     devise/registrations#edit
#                                 PUT    /users(.:format)                                          devise/registrations#update
#                                 DELETE /users(.:format)                                          devise/registrations#destroy
#            for_user_assignments GET    /users/:user_id/assignments/for(.:format)                 assignments#for
#             by_user_assignments GET    /users/:user_id/assignments/by(.:format)                  assignments#by
#                user_assignments GET    /users/:user_id/assignments(.:format)                     assignments#index
#                                 POST   /users/:user_id/assignments(.:format)                     assignments#create
#             new_user_assignment GET    /users/:user_id/assignments/new(.:format)                 assignments#new
#            edit_user_assignment GET    /users/:user_id/assignments/:id/edit(.:format)            assignments#edit
#                 user_assignment GET    /users/:user_id/assignments/:id(.:format)                 assignments#show
#                                 PUT    /users/:user_id/assignments/:id(.:format)                 assignments#update
#                                 DELETE /users/:user_id/assignments/:id(.:format)                 assignments#destroy
#                           users GET    /users(.:format)                                          users#index
#                            user GET    /users/:id(.:format)                                      users#show
#                         quizzes GET    /quizzes(.:format)                                        quizzes#index
#                                 POST   /quizzes(.:format)                                        quizzes#create

app/models/announcement_message.rb
class AnnouncementMessage < ActiveRecord::Base
  attr_accessible :author, :content, :group, :attachment, :link

  has_attached_file :attachment

  belongs_to :author, class_name: 'User'
  belongs_to :group

  validates_presence_of :author, :content

  has_many :announcements, dependent: :destroy, foreign_key: 'message_id'
  # at least one association should be there
  validates :announcements, length: { minimum: 1 }
  # if group? then has exactly group.user_size announcements
  # see {GroupSizeValidator#validates_each}
  validates :announcements, group_size: true

  # shortcut method that creates announcements records
  # returns AnnouncementMessage object itself which is
  # good to use AnnoucementMessage.new(...).announce_to(...)
  def announce_to(whom)
    if whom.is_a? User
      recipient_type = 'User'
    elsif whom.is_a? Group
      recipient_type = 'Group'
    end
    unless recipient_type.nil?
      a_list = Announcement.create_for recipient_type: recipient_type, recipient: whom do |a|
        a.sender = author
        a.message = self
      end
      a_list.each do |a|
        announcements << a
      end
    end
    self
  end

  def recipients
    announcements.map(&:recipient)
  end

end

app/controllers/announcement_messages_controller.rb
class AnnouncementMessagesController < ApplicationController
  before_filter :authenticate_user!
  # load_and_authorize_resource

  # Lists all announcements from the current_user
  def index
    if params[:user_id]
      # Renders announcements from the :user_id to the current_user
      @author = User.find(params[:user_id])
      @announcements = AnnouncementMessage.joins(:announcements).where(announcements: { recipient_id: current_user}, author_id: @author)
    else
      @announcements = AnnouncementMessage.where(author_id: current_user)
    end
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @announcements }
    end
  end

  def recipients
    @announcement_recipients = AnnouncementMessage.find(params[:id]).announcements
  end

  # gets past announcements for the current user
  def past
    @announcements = AnnouncementMessage.joins(:announcements).where(announcements: { recipient_id: current_user, showable: false}).all
  end

  def show
    @announcement = AnnouncementMessage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @announcement }
    end
  end

  def new
    @announcement = AnnouncementMessage.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @announcement }
    end
  end

  def create
    # TODO: take it out to a method or a model 
    recipient_type = params[:announcement_message][:recipient_type]
    recipient = eval("#{recipient_type}.find(params[:announcement_message][:recipient])")
    params[:announcement_message][:author] = current_user
    params[:announcement_message].delete(:recipient)
    params[:announcement_message].delete(:recipient_type)
    @announcement = AnnouncementMessage.new(params[:announcement_message]).announce_to(recipient)
    # TODO: make controller decide what to do more elegantly
    if @announcement.save
      redirect_to @announcement, notice: 'Announcement was successfully created.'
    else
     render action: "new"
    end
  end

  def update
    @announcement = AnnouncementMessage.find(params[:id])
    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to @announcement, notice: 'Announcement was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @announcement = AnnouncementMessage.find(params[:id])
    @announcement.destroy
    respond_to do |format|
      format.html { redirect_to announcement_messages_url }
      format.json { head :no_content }
    end
  end

  def unshow
    announcement = Announcement.where(message_id: params[:announcement_message_id], recipient_id: current_user ).first
    announcement.update_attribute :showable, false
    respond_to do |format|
      format.js
    end
  end
  # makes an announcement showable to the users again. Technically opposite of the unshow
  def resend
    if params[:user_id]
      # should be resend to a particular user
      announcements = Announcement.where(message_id: params[:announcement_message_id], recipient_id: params[:user_id])
    else
      # resend to all users
      announcements = Announcement.where(message_id: params[:id])
    end
    Announcement.transaction do
      announcements.each do |a|
        a.update_attribute :showable, true
      end
    end
    redirect_to :back
  end
end

app/helpers/announcement_messages_helper.rb
module AnnouncementMessagesHelper
  # Returns string that has all of the  recipients names in it
  # separated by commas. Useful in "Sent To: ..." lines.
  def recipients(announcement_message)
    announcement_message.announcements.map(&:recipient).map(&:name).join(", ")
  end
  # if only one recipient returns its name, otherwise returns links to the
  # page that has announcements listed
  def link_to_recipients_if_many_or_name(announcement_message)
    if announcement_message.recipients.size == 1
      announcement_message.recipients.first.name
    else
      link_to "Recipients", recipients_announcement_message_path(announcement_message)
    end
  end

  def display_date(input_date)
    input_date.strftime("%d %B %Y at %I:%M%p")
  end

  #
  # This method makes sure that we are not going to break if there's
  # some symbol that is not in UTF-8
  def content(announcement_message)
    announcement_message.content.encode('UTF-8', 'binary', invalid: :replace, undef: :replace, replace: '')
  end

end

app/views/announcement_messages/_form.html.haml
= simple_form_for @announcement, html: { class: 'form-vertical', multipart: true} do |f|
  = f.error_notification

  .form-inputs
    = render partial: 'shared/user_or_group', locals: { recipient_list_label: "Announce To", sendable: "announcement_message"}

    = f.input :content, input_html: { rows: 5, class: "span5"}

    = f.file_field :attachment

  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = btn_link_to "Cancel", :back

app/views/announcement_messages/_home_page_announcements.html.haml
%table#home_page_announcements.table.table-condensed
  %thead
    %th Content
    %th{width: '30px'}
    %th{width: '15%'} From
    %th{width: '15%'} Sent
  %tbody
    - @all_announcements.each do |announcement|
      %tr
        %td
          = link_to truncate(h(content(announcement))), "#modal_announcement_#{announcement.id}",  data: {toggle: "modal"}
          .modal.hide.fade{id: "modal_announcement_#{announcement.id}", role: "dialog", aria: { ehidden: "true" }}
            .modal-header
              %button{type: "button", class: "close", data: { dismiss: "modal"}, aria: { hidden: "true"}} ×
              %h3 From: #{announcement.author.name}
            .modal-body
              %p= h content(announcement)
              - if announcement.attachment?
                %p
                  = link_to announcement.attachment_file_name, announcement.attachment.url, target: "_blank"

        %td
          - if announcement.attachment?
            = link_to announcement.attachment.url, target: "_blank" do
              %i.icon-paper-clip

        %td= link_to announcement.author.name, user_announcement_messages_path(announcement.author)
        %td
          = distance_of_time_in_words_to_now announcement.updated_at
          ago

app/views/announcement_messages/_user_announcements.html.haml
- announcements.each do |ann|
  = content_tag :div, class: "alert alert-info", :id => "announcement_#{ann.id}" do
    = content_tag :a, class: "close", href: "#", data: { dismiss: "alert"}  do
      %span.small Confirm read
      &#215;
    = content_tag :div do
      %h4
        From:
        = ann.author.name
      = ann.content
      - unless ann.link.nil?
        %br
        = link_to "More", ann.link
      - if ann.attachment?
        %br
        = link_to ann.attachment_file_name, ann.attachment.url, target: "_blank"
      :javascript
        $("#announcement_#{ann.id}").bind('close', function () {
          $.ajax({
            url: "#{ announcement_message_unshow_path(ann) }"
            });
        });

app/views/announcement_messages/edit.html.haml
%h1 Editing announcement

= render 'form'

= link_to 'Show', @announcement
\|
= link_to 'Back', announcements_path

app/views/announcement_messages/index.html.haml
.page-header
  %h1
    Announcements
    - if can? :create, AnnouncementMessage
      = link_to 'Create New', new_announcement_message_path, {class: 'btn btn-success'}


%table#announcements.table.datatable
  %thead
    %th #
    %th Content
    %th Author
    %th Recipients
    %th Sent
    %th

  %tbody
    - @announcements.each_with_index do |announcement, index|
      %tr
        %td= index+1
        %td= link_to announcement.content, announcement
        %td= announcement.author.name
        %td= link_to_recipients_if_many_or_name announcement
        %td= l announcement.created_at, format: :medium
        %td
          - if can? :resend, AnnouncementMessage
            = link_to 'Resend', resend_announcement_message_path(announcement), class:'btn btn-primary resend-button', remote: true, method: :post, confirm: 'Do you want to resend this announcement?'
          - if can? :delete, AnnouncementMessage
            = link_to announcement, :confirm => 'Are you sure?', :method => :delete , class: 'btn btn-danger' do
              %i.icon-remove
:javascript
  jQuery(function($) {
    $(".resend-button")
      .bind("ajax:success", function(event, data, status, xhr) {
        $('<div id="announcement_3" class="alert alert-success"><a href="#" data-dismiss="alert" class="close">× </a><div>Announcement has been re-sent.</div></div>').insertBefore('.page-header');
      });
  });

app/views/announcement_messages/new.html.haml
%h1 New announcement

= render 'form'

= link_to 'Back', announcement_messages_path

app/views/announcement_messages/past.html.haml
%h1 Past Announcements For #{current_user.name }

%table#past_announcements.table
  %thead
    %th From
    %th Content
    %th Sent
    %th Seen
    %th
  %tbody
    - @announcements.each do |announcement|
      %tr
        %td= announcement.author.name
        %td= announcement.content
        %td= announcement.created_at.strftime("%h %d %H:%M:%S")
        %td= announcement.updated_at.strftime("%h %d %H:%M:%S")
        %td= btn_link_to 'Show', announcement

app/views/announcement_messages/recipients.html.haml
%h1 Recipient of the Announcement

%table.table
  %tr
    %th #
    %th Recipient
    %th Seen On
    %th Closed
    %th
  - @announcement_recipients.each_with_index do |ar, idx|
    %tr
      %td= idx+1
      %td= link_to ar.recipient.name, user_path(ar.recipient)
      %td= display_date(ar.updated_at) 
      %td= ar.showable ? "No" : "Yes"
      %td= btn_link_to("Resend", user_announcement_message_resend_path(ar.recipient, ar.message),  method: :post) unless ar.showable

app/views/announcement_messages/show.html.haml
.well
  %h4
    Sent To: #{recipients @announcement}
  %h5
    From: #{@announcement.author.name}
  %p
    = @announcement.content
  - unless @announcement.link.nil?
    %br
    = link_to "More", @announcement.link
  - if @announcement.attachment?
    %br
    = link_to @announcement.attachment_file_name, @announcement.attachment.url, target: "_blank"


-# = link_to 'Announcements', announcement_messages_path

app/views/announcement_messages/unshow.js.haml
// alert('Announcement will not be shown again.')