config/routes.rb
Click2Interact::Application.routes.draw do

  resources :announcement_messages, path: 'announcements' do
    get :unshow
    # shows list of past announcements for the current user
    collection do
      get :past
    end
    member do
      get :recipients
      post :resend
    end
  end

  resources :groups

  resources :paper_forms, path: 'forms' do
    resources :assignments do
      member do
        get :take
        post :complete
        get :completed
      end
    end
    resources :response_sets

    get :possible_assignees

  end

  resources :quizzes do
    resources :assignments do
      member do
        get :take
        post :complete
        get :completed
      end
    end
  end

  authenticated :user do
    root :to => 'home#index'
  end

  root :to => "pages#index"
  match '/terms' => "pages#terms"
  match '/about' => "pages#about"
  match '/faq' => "pages#faq"
  match '/changelog' => "pages#changelog"

  # authentification and registration
  devise_for :users, controllers: { registrations: "registrations", confirmations: "confirmations" } do
    # sign-up with PIN
    get "users/sign_up_with_pin", to: "registrations#new_pin"
  end
  devise_scope :user do
    put "/confirm" => "confirmations#confirm"
  end

  resources :users, :only => [:show, :index, :edit] do
    resources :assignments do
      collection do
        get 'for'
        get 'by'
      end
    end
    get 'recipient_list'
    put 'change'

    get 'new_child'
    post 'create_child'

    resources :announcement_messages, path: :announcements, only: [:resend]  do
      post :resend
    end

    resources :announcement_messages, path: :announcements, only: [:index]
    
  end

  resources :conversations, only: [:index, :show, :new, :create] do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  resources :text_messages, :path => 'sms', :only => [:index, :new, :create, :destroy]

  namespace :admin do
    resources :reports
    resources :users, :only => [:show, :edit, :index, :new, :create, :destroy] do
      put 'change'
      get 'new_child'
      post 'create_child'
      member do
        post 'approve'
        post 'disapprove'
        post 'notify'
      end
    end
    resources :user_imports

    root to: "users#index"
  end

  scope '/admin' do
    resources :reports do
      resources :assignments
    end
  end

  namespace :teacher do
    resources :reports, only: [:index], controller: 'report_submissions' do
      resources :report_submissions, only: [:new, :show, :create, :destroy] , path: 'submissions'
      get "submissions", controller: 'report_submissions'
    end
  end

  namespace :parent do
    resources :reports, only: [:index], controller: 'report_submissions' do
      resources :report_submissions, only: [:show] , path: 'submissions'
      get "submissions", controller: 'report_submissions'
    end
  end

end
#== Route Map
# Generated on 15 Oct 2012 21:50
#
#                                 POST   /groups(.:format)                                         groups#create
#                       new_group GET    /groups/new(.:format)                                     groups#new
#                      edit_group GET    /groups/:id/edit(.:format)                                groups#edit
#                           group GET    /groups/:id(.:format)                                     groups#show
#                                 PUT    /groups/:id(.:format)                                     groups#update
#                                 DELETE /groups/:id(.:format)                                     groups#destroy
#      take_paper_form_assignment GET    /forms/:paper_form_id/assignments/:id/take(.:format)      assignments#take
#  complete_paper_form_assignment POST   /forms/:paper_form_id/assignments/:id/complete(.:format)  assignments#complete
# completed_paper_form_assignment GET    /forms/:paper_form_id/assignments/:id/completed(.:format) assignments#completed
#          paper_form_assignments GET    /forms/:paper_form_id/assignments(.:format)               assignments#index
#                                 POST   /forms/:paper_form_id/assignments(.:format)               assignments#create
#       new_paper_form_assignment GET    /forms/:paper_form_id/assignments/new(.:format)           assignments#new
#      edit_paper_form_assignment GET    /forms/:paper_form_id/assignments/:id/edit(.:format)      assignments#edit
#           paper_form_assignment GET    /forms/:paper_form_id/assignments/:id(.:format)           assignments#show
#                                 PUT    /forms/:paper_form_id/assignments/:id(.:format)           assignments#update
#                                 DELETE /forms/:paper_form_id/assignments/:id(.:format)           assignments#destroy
#        paper_form_response_sets GET    /forms/:paper_form_id/response_sets(.:format)             response_sets#index
#                                 POST   /forms/:paper_form_id/response_sets(.:format)             response_sets#create
#     new_paper_form_response_set GET    /forms/:paper_form_id/response_sets/new(.:format)         response_sets#new
#    edit_paper_form_response_set GET    /forms/:paper_form_id/response_sets/:id/edit(.:format)    response_sets#edit
#         paper_form_response_set GET    /forms/:paper_form_id/response_sets/:id(.:format)         response_sets#show
#                                 PUT    /forms/:paper_form_id/response_sets/:id(.:format)         response_sets#update
#                                 DELETE /forms/:paper_form_id/response_sets/:id(.:format)         response_sets#destroy
#   paper_form_possible_assignees GET    /forms/:paper_form_id/possible_assignees(.:format)        paper_forms#possible_assignees
#                     paper_forms GET    /forms(.:format)                                          paper_forms#index
#                                 POST   /forms(.:format)                                          paper_forms#create
#                  new_paper_form GET    /forms/new(.:format)                                      paper_forms#new
#                 edit_paper_form GET    /forms/:id/edit(.:format)                                 paper_forms#edit
#                      paper_form GET    /forms/:id(.:format)                                      paper_forms#show
#                                 PUT    /forms/:id(.:format)                                      paper_forms#update
#                                 DELETE /forms/:id(.:format)                                      paper_forms#destroy
#                            root        /                                                         home#index
#                            root        /                                                         pages#index
#                new_user_session GET    /users/sign_in(.:format)                                  devise/sessions#new
#                    user_session POST   /users/sign_in(.:format)                                  devise/sessions#create
#            destroy_user_session DELETE /users/sign_out(.:format)                                 devise/sessions#destroy
#                   user_password POST   /users/password(.:format)                                 devise/passwords#create
#               new_user_password GET    /users/password/new(.:format)                             devise/passwords#new
#              edit_user_password GET    /users/password/edit(.:format)                            devise/passwords#edit
#                                 PUT    /users/password(.:format)                                 devise/passwords#update
#        cancel_user_registration GET    /users/cancel(.:format)                                   devise/registrations#cancel
#               user_registration POST   /users(.:format)                                          devise/registrations#create
#           new_user_registration GET    /users/sign_up(.:format)                                  devise/registrations#new
#          edit_user_registration GET    /users/edit(.:format)                                     devise/registrations#edit
#                                 PUT    /users(.:format)                                          devise/registrations#update
#                                 DELETE /users(.:format)                                          devise/registrations#destroy
#            for_user_assignments GET    /users/:user_id/assignments/for(.:format)                 assignments#for
#             by_user_assignments GET    /users/:user_id/assignments/by(.:format)                  assignments#by
#                user_assignments GET    /users/:user_id/assignments(.:format)                     assignments#index
#                                 POST   /users/:user_id/assignments(.:format)                     assignments#create
#             new_user_assignment GET    /users/:user_id/assignments/new(.:format)                 assignments#new
#            edit_user_assignment GET    /users/:user_id/assignments/:id/edit(.:format)            assignments#edit
#                 user_assignment GET    /users/:user_id/assignments/:id(.:format)                 assignments#show
#                                 PUT    /users/:user_id/assignments/:id(.:format)                 assignments#update
#                                 DELETE /users/:user_id/assignments/:id(.:format)                 assignments#destroy
#                           users GET    /users(.:format)                                          users#index
#                            user GET    /users/:id(.:format)                                      users#show
#                         quizzes GET    /quizzes(.:format)                                        quizzes#index
#                                 POST   /quizzes(.:format)                                        quizzes#create

app/controllers/paper_forms_controller.rb
class PaperFormsController < ApplicationController
  before_filter :authenticate_user!
  load_and_authorize_resource

  # GET /paper_forms
  # GET /paper_forms.json
  def index
    # restrict paperforms to only ones that have been created by the user
    @paper_forms = PaperForm.where(author_id: current_user)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @paper_forms }
    end
  end

  # GET /paper_forms/1
  # GET /paper_forms/1.json
  def show
    @paper_form = PaperForm.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @paper_form }
    end
  end

  # GET /paper_forms/new
  # GET /paper_forms/new.json
  def new
    @paper_form = PaperForm.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @paper_form }
    end
  end

  # GET /paper_forms/1/edit
  def edit
    @paper_form = PaperForm.find(params[:id])
  end

  # POST /paper_forms
  # POST /paper_forms.json
  def create
    @paper_form = PaperForm.new(params[:paper_form])
    @paper_form.author = current_user
    respond_to do |format|
      if @paper_form.save
        format.html { redirect_to @paper_form, notice: 'Paper form was successfully created.' }
        format.json { render json: @paper_form, status: :created, location: @paper_form }
      else
        format.html { render action: "new"}
        format.json { render json: @paper_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /paper_forms/1
  # PUT /paper_forms/1.json
  def update
    @paper_form = PaperForm.find(params[:id])
    respond_to do |format|
      if @paper_form.update_attributes(params[:paper_form])
        format.html { redirect_to @paper_form, notice: 'Paper form was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @paper_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /paper_forms/1
  # DELETE /paper_forms/1.json
  def destroy
    @paper_form = PaperForm.find(params[:id])
    @paper_form.destroy
    respond_to do |format|
      format.html { redirect_to paper_forms_url }
      format.json { head :no_content }
    end
  end

  def possible_assignees
    if params[:assignment_type] == "Group"
      @assignee_list = Group.all
    elsif params[:assignment_type] == "User"
      @assignee_list = User.all
    else
      @assignee_list = []
    end
    #respond_with(@assignee_list)
    respond_to do |format|
      format.js
    end

  end

end

app/helpers/paper_forms_helper.rb
module PaperFormsHelper
end

app/views/paper_forms/_article_fields.html.haml
.nested-fields.articles
  = f.input :content, label: 'Question', input_html: { rows: 3, class: 'span5' }
  = f.input :response_type, collection: %w(string integer float choice), selected: 'string', input_html: { onchange: "Application.show_choice_controls(this);" }
  = f.simple_fields_for :replies do |ff|
    = render 'reply_fields', f: ff

  .add-reply-action
    = link_to_add_association 'Add Options', f, :replies, { class: 'btn' }

  .remove-article
    = link_to_remove_association "Remove Question", f, { class: 'btn btn-danger' }

app/views/paper_forms/_article_show.html.haml
%p
  = article.content

%ol
  - article.replies.each do |reply|
    %li= reply.content

app/views/paper_forms/_form.html.haml
= simple_form_for @paper_form, :wrapper => :bootstrap, :html => { :class => 'form-horizontal' } do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    .form-articles
      = f.simple_fields_for :articles do |ff|
        = render 'article_fields', f: ff
      .add-article-action
        = link_to_add_association 'Add Question', f, :articles, { class: 'btn' }

  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = btn_link_to "Cancel", :back

app/views/paper_forms/_home_page_forms.html.haml
.tabbable
  %ul.nav.nav-tabs#form_status_tab
    %li.active
      %a{href: "#pending", data: {toggle: "tab"}} Pending
    %li
      %a{href: "#completed", data: {toggle: "tab"}} Completed

  .tab-content
    .tab-pane.active#pending
      %table.home_page_forms.table
        %thead
          %th Title
          %th Due Date
          %th Status
          %th
        %tbody
          - @form_assignments.pending.each do |assignment|
            %tr
              %td= link_to assignment.assignable.title, assignment.assignable
              %td= l assignment.due_date, format: :medium
              %td= assignment_status(assignment)
              %td
                - if can? :fill, PaperForm
                  = btn_link_to 'Fill The Form', take_paper_form_assignment_path(assignment.assignable, assignment)

    .tab-pane#completed
      %table.home_page_forms.table
        %thead
          %th Title
          %th Due Date
          %th Status
          %th
        %tbody
          - @form_assignments.completed.each do |assignment|
            %tr
              %td= link_to assignment.assignable.title, completed_paper_form_assignment_path(assignment.assignable, assignment)
              %td= l assignment.due_date, format: :medium
              %td= assignment_status(assignment)
              %td

app/views/paper_forms/_reply_fields.html.haml
.nested-fields.replies
  = f.input :content, label: 'Answer', input_html: { rows: 3, class: 'span3' }

  .remove-reply
    = link_to_remove_association "Remove", f, { class: 'btn btn-danger'}

app/views/paper_forms/edit.html.haml
.page-header
  %h1
    Edit Form
    %small edit form before you assign it.

= render 'form'

app/views/paper_forms/index.html.haml
.page-header
  %h1 
    Forms
    %small Forms that you have authored and/or can send for completion to other users.

%p.text-info

%table.table#paper_forms
  %thead
    %th Title
    %th Created
    %th Author
    %th
    %th
    %th
  %tbody
    - @paper_forms.each do |paper_form|
      %tr
        %td= link_to paper_form.title, paper_form
        %td= l paper_form.created_at, format: :medium
        %td= paper_form.author.name
        %td= link_to 'Assignments', paper_form_assignments_path(paper_form)
        %td= paper_form.assignments_completed?
        %td
          - if can? :edit, PaperForm
            = btn_link_to 'Edit', edit_paper_form_path(paper_form)
          = btn_link_to 'Assign', new_paper_form_assignment_path(paper_form)
          - if can? :delete, PaperForm
            = link_to paper_form, :confirm => 'Are you sure?', :method => :delete , class: 'btn btn-danger' do
              %i.icon-remove

.well
  = btn_link_to 'New Paper form', new_paper_form_path

app/views/paper_forms/new.html.haml
.page-header
  %h1 Create New Form

= render 'form'

app/views/paper_forms/possible_assignees.js.haml
$('#assignment_recipient').html("#{j  options_from_collection_for_select(@assignee_list, :id, :name)}")

app/views/paper_forms/show.html.haml
.page-header
  %h1= h @paper_form.title

- @paper_form.articles.each do |article|
  -# = render 'article_show', locals: { article: article }
  .well
    %p
      = h article.content

    %ol
      - article.replies.each do |reply|
        %li= h reply.content

.well
  - if can? :edit, PaperForm
    = btn_link_to 'Edit', edit_paper_form_path(@paper_form)
  = btn_link_to "Show Forms", paper_forms_path
  - if can? :assign, PaperForm
    = btn_link_to 'Assign', new_paper_form_assignment_path(@paper_form)